
name: Run tests (vitest)
on: push

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test